# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpusimulator.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12gpusimulator.proto\x12\x0cgpusimulator\"0\n\x05Input\x12\x16\n\x0esubexperiments\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65vices\x18\x02 \x01(\t\"7\n\x11GetCircuitRequest\x12\"\n\x05input\x18\x01 \x01(\x0b\x32\x13.gpusimulator.Input\"%\n\x12GetCircuitResponse\x12\x0f\n\x07results\x18\x01 \x01(\t2e\n\x0cGPUSimulator\x12U\n\x0e\x45xecuteCircuit\x12\x1f.gpusimulator.GetCircuitRequest\x1a .gpusimulator.GetCircuitResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gpusimulator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUT']._serialized_start=36
  _globals['_INPUT']._serialized_end=84
  _globals['_GETCIRCUITREQUEST']._serialized_start=86
  _globals['_GETCIRCUITREQUEST']._serialized_end=141
  _globals['_GETCIRCUITRESPONSE']._serialized_start=143
  _globals['_GETCIRCUITRESPONSE']._serialized_end=180
  _globals['_GPUSIMULATOR']._serialized_start=182
  _globals['_GPUSIMULATOR']._serialized_end=283
# @@protoc_insertion_point(module_scope)
