# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gpusimulator_pb2 as gpusimulator__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gpusimulator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GPUSimulatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCircuit = channel.unary_unary(
                '/gpusimulator.GPUSimulator/ExecuteCircuit',
                request_serializer=gpusimulator__pb2.GetCircuitRequest.SerializeToString,
                response_deserializer=gpusimulator__pb2.ExecuteCircuitResponse.FromString,
                _registered_method=True)
        self.CheckJobStatus = channel.unary_unary(
                '/gpusimulator.GPUSimulator/CheckJobStatus',
                request_serializer=gpusimulator__pb2.CheckJobStatusRequest.SerializeToString,
                response_deserializer=gpusimulator__pb2.CheckJobStatusResponse.FromString,
                _registered_method=True)


class GPUSimulatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteCircuit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GPUSimulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCircuit': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCircuit,
                    request_deserializer=gpusimulator__pb2.GetCircuitRequest.FromString,
                    response_serializer=gpusimulator__pb2.ExecuteCircuitResponse.SerializeToString,
            ),
            'CheckJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckJobStatus,
                    request_deserializer=gpusimulator__pb2.CheckJobStatusRequest.FromString,
                    response_serializer=gpusimulator__pb2.CheckJobStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gpusimulator.GPUSimulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gpusimulator.GPUSimulator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GPUSimulator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteCircuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpusimulator.GPUSimulator/ExecuteCircuit',
            gpusimulator__pb2.GetCircuitRequest.SerializeToString,
            gpusimulator__pb2.ExecuteCircuitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpusimulator.GPUSimulator/CheckJobStatus',
            gpusimulator__pb2.CheckJobStatusRequest.SerializeToString,
            gpusimulator__pb2.CheckJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
