# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpusimulator.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'gpusimulator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12gpusimulator.proto\x12\x0cgpusimulator\"0\n\x05Input\x12\x16\n\x0esubexperiments\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65vices\x18\x02 \x01(\t\"7\n\x11GetCircuitRequest\x12\"\n\x05input\x18\x01 \x01(\x0b\x32\x13.gpusimulator.Input\"(\n\x16\x45xecuteCircuitResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\'\n\x15\x43heckJobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\":\n\x16\x43heckJobStatusResponse\x12\x0f\n\x07is_done\x18\x01 \x01(\x08\x12\x0f\n\x07results\x18\x02 \x01(\t2\xc8\x01\n\x0cGPUSimulator\x12Y\n\x0e\x45xecuteCircuit\x12\x1f.gpusimulator.GetCircuitRequest\x1a$.gpusimulator.ExecuteCircuitResponse\"\x00\x12]\n\x0e\x43heckJobStatus\x12#.gpusimulator.CheckJobStatusRequest\x1a$.gpusimulator.CheckJobStatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gpusimulator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUT']._serialized_start=36
  _globals['_INPUT']._serialized_end=84
  _globals['_GETCIRCUITREQUEST']._serialized_start=86
  _globals['_GETCIRCUITREQUEST']._serialized_end=141
  _globals['_EXECUTECIRCUITRESPONSE']._serialized_start=143
  _globals['_EXECUTECIRCUITRESPONSE']._serialized_end=183
  _globals['_CHECKJOBSTATUSREQUEST']._serialized_start=185
  _globals['_CHECKJOBSTATUSREQUEST']._serialized_end=224
  _globals['_CHECKJOBSTATUSRESPONSE']._serialized_start=226
  _globals['_CHECKJOBSTATUSRESPONSE']._serialized_end=284
  _globals['_GPUSIMULATOR']._serialized_start=287
  _globals['_GPUSIMULATOR']._serialized_end=487
# @@protoc_insertion_point(module_scope)
